### ISSUE TITLE
Multiple types for property (PHP Annotation to JSON schema)

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/psx-schema#11]
I'm trying to generate a JSON schema from PHP Annoations. This works great as long as my properties have a single type (either string or integer or ...), but I have some properties which have type integer AND type null. 
In JSON schema this can be written as ```{ "type": ["integer", "null"] }``` ([JSON schema](https://spacetelescope.github.io/understanding-json-schema/reference/type.html#type)), but I couldn't find a way to generate such a JSON schema with the @Type anonnation.

Do I miss something or does the @Type annoation only support a single type?
Would you be interested in a PR to add this feature and if so which syntax would you expect?

**Workaround:**
```@OneOf(@Schema(type="integer"), @Schema(type="null"))```

**Comment by chriskapp** [comment]
Hi, so I think it should be possible to use the type annotation with a simple array syntax i.e.:

```
@Type({"integer", "null"})
```

Through this we should generate a `PropertyType` object which contains an array as type. That being said I have not tested this case so please let me know whether this works. Otherwise your workaround is of course also valid.

**Comment by christoph-bessei** [comment]
Thanks for your help, your suggestions works perfectly!
