### ISSUE TITLE
Traverse assoc array instead of stdClass with json_decode

### ISSUE THREAD

**Issue by ruudk** [apioo/psx-schema#19]
I'm coming from an ancient version of psx-schema (https://github.com/apioo/psx-schema/commit/10446f644a7bffc87329fa7d22a615962f1116ed). There, it was possible to traverse `array` to an object. 

Since I updated to the latest version, I get this error:
```
PSX\Schema\ValidationException: / must be of type object

vendor/psx/schema/src/SchemaTraverser.php:477
vendor/psx/schema/src/SchemaTraverser.php:101
vendor/psx/schema/src/SchemaTraverser.php:83
```

My code is as follows:
```php
use PSX\Schema\Parser\Popo\Annotation\AdditionalProperties;
use PSX\Schema\Parser\Popo\Annotation\Description;
use PSX\Schema\Parser\Popo\Annotation\Key;
use PSX\Schema\Parser\Popo\Annotation\Required;
use PSX\Schema\Parser\Popo\Annotation\Title;
use PSX\Schema\Parser\Popo\Annotation\Type;

/**
 * @Title("Interest")
 * @Description("POST /api/interest <br>Can be used relate a user to an event that at some point has been interesting. Useful for recommendations.")
 * @AdditionalProperties(false)
 */
class Interest
{
    /**
     * @Key("userId")
     * @Type("string")
     * @Required
     *
     * @var string
     */
    private $userId;

    /**
     * @Key("eventId")
     * @Type("string")
     * @Required
     *
     * @var string
     */
    private $eventId;

    /**
     * @return string
     */
    public function getUserId() : string
    {
        return $this->userId;
    }

    /**
     * @param string $userId
     */
    public function setUserId(string $userId)
    {
        $this->userId = $userId;
    }

    /**
     * @return string
     */
    public function getEventId() : string
    {
        return $this->eventId;
    }

    /**
     * @param string $eventId
     */
    public function setEventId(string $eventId)
    {
        $this->eventId = $eventId;
    }
}

$data = [
    'userId'  => '1',
    'eventId' => '9df073ed-acb2-466c-9207-da166f3148dc',
];
$schemaName = Interest::class;

$schema = $this->managerschemaManager->getSchema($schemaName);
$traverser = new SchemaTraverser();

return $traverser->traverse($data, $schema, new TypeVisitor());
```

Is it correct that this is no longer supported? And that I should instead provide a `stdClass` with the data?

**Comment by chriskapp** [comment]
Hi, yes we have changed this behaviour to follow `json_decode` which returns a `stdClass` instead of an array. In your example you would need to write:
```
$data = (object) [
    'userId'  => '1',
    'eventId' => '9df073ed-acb2-466c-9207-da166f3148dc',
];
```

This is done on the PHP side to distinguish clean between array and objects. If we only use arrays (assoc array for JSON objects and index array for JSON array) we cant know the type if we receive an empty array, whether it is an object or array. Because of this PHP `json_decode` returns a `stdClass`. In most cases the data comes directly from `json_decode` so you only need to call it without assoc option.

We have also a helper function to turn any array structure into objects please take a look at `PSX\Data\Util\CurveArray::objectify`

**Comment by chriskapp** [comment]
I will close this issue since it looks like there is nothing more to do here
